function data()
return {
	vehicles = {
        { name = "vehicle/waggon/ICEL/Bpdz1.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz2.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz3.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz4.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz5.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz6.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz7.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz8.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz9.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz10.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz11.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpz12.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/Bpbsz13.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/WRz14.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/Apz15.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/Apz16.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/Apzf17.mdl", forward = false },
	},
	name = _("ICEL_pulled_name"),
	desc = _("ICEL_desc"),
    groupFileName = "vehicle/waggon/ICEL/menu_ICEL.mdl",
}
end
