function data()
return {
	vehicles = {
        { name = "vehicle/waggon/ICEL/fake/Bpdz1.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz2.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz3.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz4.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz5.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz6.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz7.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz8.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz9.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz10.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz11.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpz12.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = true },
		{ name = "vehicle/waggon/ICEL/fake/Bpbsz13.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/fake/WRz14.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/fake/Apz15.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/fake/Apz16.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/laufwerk.mdl", forward = false },
		{ name = "vehicle/waggon/ICEL/fake/Apzf17.mdl", forward = false },
	},
	name = _("ICEL_pulled_name_fake"),
	desc = _("ICEL_desc"),
    groupFileName = "vehicle/waggon/ICEL/fake/menu_ICEL_fake.mdl",
}
end
